modLoader = "javafml"
loaderVersion = "[38,)"
issueTrackerURL = "https://github.com/kb-1000/no-telemetry/issues"
license = "CC0"

[[mods]]
modId = "no_telemetry"
version = "${file.jarVersion}"
displayName = "No Telemetry Plus"
description = "Disable or anonymize the telemetry introduced in 21w38a"
logoFile = "no-telemetry-icon.png"
logoBlur = false
authors = "kb1000, IMS"
displayURL = "https://github.com/IMS212/no-telemetry-plus"

[[no-telemetry.dependencies]]
modId = "minecraft"
mandatory = true
# no versionRange, let's rely on the loader version
